"""empty message

Revision ID: 4675240dd81c
Revises: 
Create Date: 2022-01-01 12:25:46.818581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4675240dd81c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_title', sa.String(length=150), nullable=True),
    sa.Column('movie_year', sa.Integer(), nullable=True),
    sa.Column('movie_director', sa.Text(), nullable=True),
    sa.Column('sound_director', sa.String(length=150), nullable=True),
    sa.Column('imdb', sa.Float(), nullable=True),
    sa.Column('Netflix', sa.Boolean(), nullable=True),
    sa.Column('Hulu', sa.Boolean(), nullable=True),
    sa.Column('Prime', sa.Boolean(), nullable=True),
    sa.Column('Disney', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('Language', sa.String(length=150), nullable=True),
    sa.Column('runtime', sa.String(length=10), nullable=True),
    sa.Column('movie_age_rating', sa.String(length=10), nullable=True),
    sa.Column('poster_url', sa.String(length=200), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('Netflix', sa.Boolean(), nullable=False),
    sa.Column('Disney', sa.Boolean(), nullable=False),
    sa.Column('Prime', sa.Boolean(), nullable=False),
    sa.Column('Hulu', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=30), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('music_director', sa.String(length=150), nullable=True),
    sa.Column('album_name', sa.String(length=300), nullable=True),
    sa.Column('track_name', sa.String(length=300), nullable=True),
    sa.Column('preview_url', sa.String(length=300), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Songs')
    op.drop_table('Genres')
    op.drop_table('Features')
    op.drop_table('Favorites')
    op.drop_table('Users')
    op.drop_table('Movies')
    # ### end Alembic commands ###
